backend:
  name: github
  repo: admarin333333/estudio-contable
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: novedades
    label: Novedades
    folder: "content/novedades"
    create: true
    slug: "{{slug}}"
    format: frontmatter
    extension: md

    fields:
      - name: titulo
        label: Título
        widget: string
      - name: fecha
        label: Fecha
        widget: datetime
      - name: texto
        label: Texto breve
        widget: string
      - name: contenido
        label: Contenido
        widget: markdown
      - name: imagen
        label: Imagen
        widget: image